# ===========================================
# ESP32-C6 Smart Controller
# ===========================================
# This configuration is for an ESP32-C6 device that:
#  - Uses Wi-Fi 
#  - Displays information on an SSD1306 OLED
#  - Supports Home Assistant integration
#  - Provides OTA firmware updates
#  - Exposes a web server on port 80
#
# Users can set device names, and customize display options.

# -------------------------------------------------
# Substitutions: variables that make the file easier
# to customize by allowing changes in one place.
# -------------------------------------------------
substitutions:
  device_name: "esp32_controller"                     # Main name for the ESPHome device
  fallback_ssid: "Smart Fallback Hotspot"             # SSID for fallback AP
  fallback_password: "DefaultPassword123"             # Password for fallback AP
  ota_password: "2eac13bfeea21fd59a7926e874d5127a"    # OTA password
  display_switch_name: "Display On/Off"               # Name for the OLED display switch
  button1_name: "Button 1"                            # Name for Button 1
  button2_name: "Button 2"                            # Name for Button 2
  button4_name: "Button 4"                            # Name for Button 4

esphome:
  name: ${device_name}

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# -------------------------------------------------
# Logger: Enables logs from the device.
# -------------------------------------------------
logger:

# -------------------------------------------------
# OTA: Over-The-Air updates with a password.
# -------------------------------------------------
ota:
  - platform: esphome
    password: "${ota_password}"

# -------------------------------------------------
# Wi-Fi Configuration: Connects the device to Wi-Fi
# Only enabled if use_ethernet is set to "false"
# -------------------------------------------------
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 0s


# -------------------------------------------------
# I²C Setup for OLED Display & Future Sensors
# -------------------------------------------------
i2c:
  sda: GPIO18
  scl: GPIO19
  scan: true

# -------------------------------------------------
# Web Server: Allows local access and debugging.
# -------------------------------------------------
web_server:
  port: 80

# -------------------------------------------------
# Font Configuration for the OLED Display
# -------------------------------------------------
font:
  - file: "fonts/RobotoMono-Regular.ttf"
    id: font1
    size: 10

# -------------------------------------------------
# Display Switch: Allows turning the OLED on/off
# -------------------------------------------------
switch:
  - platform: template
    name: "${display_switch_name}"
    id: display_switch
    optimistic: true
    restore_mode: ALWAYS_ON

# -------------------------------------------------
# SSD1306 OLED Display Configuration
# Displays Wi-Fi or Ethernet status based on config.
# -------------------------------------------------
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    id: ssd1306_display
    pages:
      - id: page1
        lambda: |-
          static int load_time = 0;
          static float last_signal_strength = -100.0;
          static int last_uptime_minutes = -1;

          if (id(ip_address).state.empty() || load_time < 15) {
            // Loading animation with a progress bar
            it.clear();
            load_time++;
            int progress = (load_time * 100) / 15; // Load time in seconds
            if (progress > 100) progress = 100;

            // Draw a simple square border around the loading bar
            it.rectangle(10, 20, 108, 10);  // Border for the progress bar

            // Draw the progress bar fill
            it.filled_rectangle(12, 22, (104 * progress) / 100, 6); // Progress fill

            // Center the percentage display above the bar
            it.printf(54, 5, id(font1), "%d%%", progress); // Percentage text
          } else {
            // Display Wi-Fi signal strength as bars only if the signal has changed significantly
            it.clear();
            float strength = id(wifi_signal_sensor).state;
            int x = 0;
            int y = 15;

            // Only update if the signal strength changes by more than 5 dBm
            if (abs(strength - last_signal_strength) > 5) {
                last_signal_strength = strength;
            }

            // Draw signal strength bars based on Wi-Fi strength
            if (strength > -80) it.filled_rectangle(x + 10, y - 4, 3, 4);    // Bar 1
            if (strength > -70) it.filled_rectangle(x + 15, y - 6, 3, 6);   // Bar 2
            if (strength > -60) it.filled_rectangle(x + 20, y - 8, 3, 8); // Bar 3
            if (strength > -50) it.filled_rectangle(x + 25, y - 10, 3, 10); // Bar 4
            if (strength > -40) it.filled_rectangle(x + 30, y - 12, 3, 12); // Bar 5

            // Display IP address above the bottom edge
            it.printf(0, 22, id(font1), "IP: %s", id(ip_address).state.c_str());
            
            // Display the uptime in days, hours, and minutes
            int uptime_seconds = (int) id(uptime_sensor).state;
            int days = uptime_seconds / 86400;
            int hours = (uptime_seconds % 86400) / 3600;
            int minutes = (uptime_seconds % 3600) / 60;
            it.printf(70, 5, id(font1), "%dd %dh %dm", days, hours, minutes);
          }
      
      - id: empty_page
        lambda: |-
          it.clear();

# -------------------------------------------------
# Binary Sensors for GPIO Inputs (Future Expansion)
# -------------------------------------------------
binary_sensor:
  - platform: gpio
    name: "${button1_name}"
    pin:
      number: GPIO13
      mode: INPUT_PULLUP

  - platform: gpio
    name: "${button2_name}"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP

  - platform: gpio
    name: "${button4_name}"
    pin:
      number: GPIO16
      mode: INPUT_PULLUP

# -------------------------------------------------
# Wi-Fi Signal Strength and Uptime Sensors
# -------------------------------------------------
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    id: wifi_signal_sensor
    update_interval: 60s

  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    update_interval: 60s

# -------------------------------------------------
# Wi-Fi Info Text Sensor to Display IP Address
# -------------------------------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      id: ip_address
    ssid:
      name: "WiFi SSID"
