# ===========================================
# ESP32-C6 Ethernet Controller
# ===========================================
# This configuration uses Ethernet (W5500)
# and displays minimal info on an SSD1306.
#
# Adjust the substitutions below to rename
# the device, buttons, or display switch.
# ===========================================

# -------------------------------------------------
# Substitutions: variables that can be referenced
# throughout the config, making it easy to update
# certain values in one place.
# -------------------------------------------------
substitutions:
  device_name: "ethernet-controller"  # Main device name (Home Assistant entity)
  display_switch_name: "Display On/Off"
  button1_name: "Button 1"
  button2_name: "Button 2"
  button4_name: "Button 4"
  # You can add more here if needed (e.g. sensor_name, etc.)

esphome:
  name: ${device_name}

# -------------------------------------------------
# Board & Framework: Using ESP32-C6 with ESP-IDF
# -------------------------------------------------
esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
api:

ota:
  - platform: esphome
    password: !secret ota_password
 
# -------------------------------------------------
# Ethernet Configuration (W5500)
# -------------------------------------------------
ethernet:
  type: w5500
  cs_pin: GPIO4
  mosi_pin: GPIO5
  miso_pin: GPIO7
  clk_pin: GPIO6
  interrupt_pin: GPIO10
  reset_pin: GPIO3

# -------------------------------------------------
# Web Server on port 80
# -------------------------------------------------
web_server:
  port: 80

# -------------------------------------------------
# I2C: For SSD1306 or other sensors
# -------------------------------------------------
i2c:
  sda: GPIO18
  scl: GPIO19
  scan: true

# -------------------------------------------------
# Font for the OLED Display
# -------------------------------------------------
font:
  - file: "fonts/RobotoMono-Regular.ttf"
    id: font1
    size: 10

# -------------------------------------------------
# Display Switch
# -------------------------------------------------
switch:
  - platform: template
    name: "${display_switch_name}"  # uses substitution
    id: display_switch
    optimistic: true
    restore_mode: ALWAYS_ON

# -------------------------------------------------
# SSD1306 Display: Just show \"Ethernet Mode\" + IP
# -------------------------------------------------
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    id: ssd1306_display
    pages:
      - id: main_page
        lambda: |-
          it.clear();
          // Simple display for Ethernet mode
          it.printf(0, 0, id(font1), "Ethernet Mode");
          it.printf(0, 15, id(font1), "IP: %s", id(ip_address).state.c_str());

      - id: empty_page
        lambda: |-
          it.clear();

# -------------------------------------------------
# Example GPIO Buttons
# -------------------------------------------------
binary_sensor:
  - platform: gpio
    name: "${button1_name}"
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    filters:
      - invert:

  - platform: gpio
    name: "${button2_name}"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    filters:
      - invert:

  - platform: gpio
    name: "${button4_name}"
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
    filters:
      - invert:

# -------------------------------------------------
# Uptime Sensor
# -------------------------------------------------
sensor:
  - platform: uptime
    name: "Ethernet Uptime"
    id: uptime_sensor
    update_interval: 60s

# -------------------------------------------------
# Text Sensor for IP Address
# If your ESPHome version supports ethernet_info, use that instead
# e.g.:
#
text_sensor:
  - platform: ethernet_info
    ip_address:
      name: "Ethernet IP Address"
      id: ip_address
# -------------------------------------------------
# text_sensor:
#   - platform: wifi_info
#     ip_address:
#       name: "IP Address"
#       id: ip_address
#     ssid:
#       name: "WiFi SSID"
